### ISSUE TITLE
Cannot merge mobileconfig hashes

### ISSUE THREAD

**Issue by groob** [dayglojesus/managedmac#74]
If I have a hierarchy like 

```yaml
:hierarchy:
  - "%{clientcert}"
  - "%{operatingsystem}"
  - global
```

and would like to apply a profile to only a specific client, while having a default set of profiles for all my Macs. Only the profiles at the top of the hierarchy(clientcert) are applied, and anything in Darwin.yaml is ignored. 

Here's a sample: 

```yaml
# Darwin.yaml
---
classes:
  - managedmac
managedmac::mobileconfigs::defaults:
  description:  'Installed by Puppet.'
  organization: 'MyOrg'
managedmac::mobileconfigs::payloads:
  'com.apple.Safari':
    content:
      HomePage: 'http://google.com/'
      NewWindowBehavior: '0'
      DomainsToNeverSetUp:
        - google.com
      PayloadType: 'com.apple.Safari'
    displayname: 'Managed Mac: Safari Settings'
```

```yaml
# myclientcert.yaml
---

managedmac::mobileconfigs::payloads:
 'com.google.Chrome':
   content:
     EnabledPlugins:
       - 'Box Edit'
     PayloadType: 'com.google.Chrome'
   displayname: 'Managed Mac: Chrome Settings
```

Only the payload for the clientcert is executed.
I thought I could use the [hash merging](https://docs.puppetlabs.com/hiera/1/lookup_types.html#hash-merge) functionality to get this to work. Currently I can only apply profiles on a global level. 

Not sure if this is a bug or if I'm doing something wrong.
