### ISSUE TITLE
hiera remove profile

### ISSUE THREAD

**Issue by clburlison** [dayglojesus/managedmac#87]
Is it possible to remove a profile that has been installed with hiera using hiera? 

Install example:
```yaml
managedmac::mobileconfigs::payloads:
  'com.apple.Safari':
    displayname: 'Safari Settings'
    content:
    - PayloadContent:
        com.apple.Safari:
          Forced:
          - mcx_preference_settings:
              HomePage: 'http://www.birdvilleschools.net'
              NewWindowBehavior: '0'
      PayloadType: com.apple.ManagedClient.preferences
```

Remove example:
```yaml
managedmac::mobileconfigs::payloads:
  'com.apple.Safari':
    ensure: absent
```

The following makes me think it is possible [mobileconfig.rb#L47-L50](https://github.com/dayglojesus/managedmac/blob/master/lib/puppet/type/mobileconfig.rb#L47-L50) but I'm not getting it to work. Am I missing something?
